services:
  - type: web
    name: answerpoint
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      rm -rf .venv
      find . -name "*.pyc" -delete
      find . -name "__pycache__" -delete
    startCommand: gunicorn run:app
